id: A584694E5
title: 'A Drop of Sunshine: A Guru Yoga for Lord Marpa'
type: translation
pechas:
- I103990E7
- I5B64DB5E
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:45:11.462734
  last_modified_at: 2023-01-04 12:45:11.462754
  collections:
  - Jokyab Pema Trinlé Nyingpo
  - Works of Tibetan Masters
alignment_to_base:
  I103990E7/5077: 1C0D
  I5B64DB5E/532D: 1C0D
